### ISSUE TITLE
echo issues 

### ISSUE THREAD

**Issue by mariannacbm34** [DivachiLeonerd/minishell#48]
![image](https://github.com/DivachiLeonerd/minishell/assets/113458788/e910ec26-9aeb-43de-80bf-958d22fb6a07)

![image](https://github.com/DivachiLeonerd/minishell/assets/113458788/51e8a4a5-26d8-4b61-9bae-0a274b9fbc4a)

![image](https://github.com/DivachiLeonerd/minishell/assets/113458788/093da8e5-fede-41ec-aaa5-5565131790dd)

**Comment by BunyMan** [comment]
Ah bom :)

**Comment by BunyMan** [comment]
FIXED
