### ISSUE TITLE
cat error message

### ISSUE THREAD

**Issue by mariannacbm34** [DivachiLeonerd/minishell#49]
![image](https://github.com/DivachiLeonerd/minishell/assets/113458788/f69cfc0f-5368-4315-942f-79373c6efb62)

> É suposto aparecer **_cat: oi: No such file or directory_**

![image](https://github.com/DivachiLeonerd/minishell/assets/113458788/28141bf7-16d8-4d86-b826-ddcbeb53fa11)

> Não é suposto aparecer essa mensagem de error

**Comment by BunyMan** [comment]
Won't fix because it's not important enough
