### ISSUE TITLE
(Não sei se é um problema) cat << oi

### ISSUE THREAD

**Issue by mariannacbm34** [DivachiLeonerd/minishell#50]
![image](https://github.com/DivachiLeonerd/minishell/assets/113458788/7ccb3845-e646-4a23-868f-1359434d153b)

> **Tive a ver que no bash o crtl +c funciona para parar, mas não sei se vcs tem que arrumar isso**

//bash
![image](https://github.com/DivachiLeonerd/minishell/assets/113458788/a64ca9f5-acb4-49c4-ba49-34bfb1e47b2a)

**Comment by BunyMan** [comment]
It's fixed enough to the point where we don't really care about it/ don't think it's a problem anymore
